[project]
name = "ReCiel"
version = "0.1.0"
description = "Generic Discord Bot built with discord.py"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py[voice]>=2.6.0",
    "python-dotenv>=1.1.1", 
]
